int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int x);
int print_last_digit(int r);
void jack_bauer(void);
void skeleton(int n);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void number(int n);
